apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: statemachine
  # This is an extra long description with Markdown
  description: |
    [The Statemachine Server](http://github.com/massenz/go-statemachine)
    exposes a gRPC API to manage statemachines and relative configurations,
    and a PubSub API to receive events for those.
  links:
    - url: https://github.com/massenz/go-statemachine
      title: GitHub Repo
      icon: github
spec:
  type: service
  lifecycle: beta
  owner: Marco Massenzio
  providesApis:
    - statemachines
    - configurations
    - events
