apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    crashoverride.com/artifact: "fsm-server"
    crashoverride.com/component: "go-statemachine"

  name: statemachine
  title: 'Statemachine Server (gRPC)'
  description: |
    [The Statemachine Server](http://github.com/massenz/go-statemachine)
    exposes a gRPC API to manage statemachines and relative configurations,
    and a PubSub API to receive events for those.
  links:
    - url: https://github.com/massenz/go-statemachine
      title: GitHub Repo
      icon: github
    - url: https://github.com/massenz/go-statemachine/releases
      title: Releases
      icon: settings
spec:
  type: service
  lifecycle: experimental
  owner: user:marco
  team: Backend
  providesApis:
    - statemachines
    - configurations
    - events
