#!/usr/bin/env bash
#
# Copyright (c) 2022 AlertAvert.com.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0
# http://www.apache.org/licenses/LICENSE-2.0
#
# Author: Marco Massenzio (marco@alertavert.com)
#
set -eu
workdir=$(dirname $0)


version=$(grep -E '^[[:blank:]]*version' ${workdir}/build.settings |\
    sed -E 's/^[[:blank:]]*version[[:blank:]]*=?[[:blank:]]*//' |\
    sed "s/'//g" | sed 's/[[:blank:]]*$//')

echo "v${version}-g$(git rev-parse --short HEAD)"
