# Copyright (c) 2023-2024 AlertAvert.com
# All rights reserved.
# Created by Marco Massenzio, 2023-07-13

name: fsm-server
version: 0.12.2
description: A StateMachine gRPC server, backed by Redis storage
author: Marco Massenzio (marco@alertavert.com)
license: Apache-2.0
url: https://alertavert.com/statemachine
