# Copyright AlertAvert Inc. (c) 2022. All rights reserved.
#
# Docker Compose for Statemachine local development ONLY.

version: '3.2'
services:
  redis:
    container_name: "redis"
    image: "redis:6.2-alpine"
    hostname: redis
    command: "redis-server --save 60 1 --loglevel warning"
    volumes:
      - "${TMPDIR:-/tmp}/redis:/data"
    ports:
      - "6379:6379"
    networks:
      - sm-net

  localstack:
    container_name: "awslocal"
    image: "localstack/localstack:1.3"
    hostname: awslocal
    environment:
      - AWS_REGION=us-west-2
      - EDGE_PORT=4566
      - SERVICES=sqs
    ports:
      - '4566:4566'
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - sm-net

# To connect to the servers in this stack, from a docker run
# via Docker, use `--network statemachine_backend`.
# The hosts listed above will then be reachable at the given names,
# on whatever ports are exposed.
networks:
  sm-net:
    ipam:
      config:
      - subnet: 172.1.1.0/24
