name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: arduino/setup-protoc@v1
      with:
        version: '3.19'
    
    - name: Install protoc-gen
      run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

    - name: Build
      run: export GOPATH=/home/runner/go && mkdir -p ${GOPATH}/bin && make all
      
    - name: Run Containers
      run: docker-compose up -d
      
    - name: Copy Bogus AWS creds
      run: mkdir -p ${HOME}/.aws && cp data/credentials ${HOME}/.aws/
      
    - name: Test
      run: go test ./api ./pubsub ./server ./storage
