# Automated PR Review from ChatGPT
#
# Copyright (c) 2023 AlertAvert.com.  All rights reserved.
# Author: Marco Massenzio (marco@alertavert.com)
#
# See: https://github.com/fluxninja/openai-pr-reviewer

name: "LLM Code Review"

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write
  contents: read
env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OpenAI PR Reviewer
        uses: coderabbitai/openai-pr-reviewer@v1
        with:
          language: en
          debug: false
          max_files: 20
          review_comment_lgtm: false
          review_simple_changes: false

      - name: Handle failure
        if: ${{ failure() }}
        run: |
          echo "### OpenAI PR Reviewer failed ❌"
          exit 1
